/*

 BKMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : C:\Users\Bootay\Desktop\New Project\Map\bkg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bkmapWidth 32
#define bkmapHeight 18
#define bkmapBank 0

extern unsigned char bkmap[];

/* End of BKMAP.H */
