/*

 LVL2-2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : C:\Users\Bootay\Desktop\New Project Scrolling\Map\bkg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define lvl22Width 32
#define lvl22Height 18
#define lvl22Bank 0

extern unsigned char lvl22[];

/* End of LVL2-2.H */
