/*

 LVL2-1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\Bootay\Desktop\New Project Scrolling\Map\bkg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define lvl21Width 20
#define lvl21Height 18
#define lvl21Bank 0

extern unsigned char lvl21[];

/* End of LVL2-1.H */
